### Address Book API Testing File


### Get All Contacts
GET http://localhost:8080/contacts
Accept: application/json


### Add New Contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Rishita",
  "lastName": "Sharma",
  "address": "Street 15",
  "city": "Up",
  "state": "up",
  "zip": "211006",
  "phoneNumber": "9876543210",
  "email": "rishita@gmail.com"
}


### Add Another Contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Hardik",
  "lastName": "Verma",
  "address": "Sector 10",
  "city": "Noida",
  "state": "Uttar Pradesh",
  "zip": "201301",
  "phoneNumber": "9123456780",
  "email": "hardik@gmail.com"
}


### Get Contact By ID
GET http://localhost:8080/contacts/1
Accept: application/json


### Update Contact
PUT http://localhost:8080/contacts/1
Content-Type: application/json

{
  "firstName": "Rishita",
  "lastName": "Sharma",
  "address": "Street 45",
  "city": "Gurgaon",
  "state": "Haryana",
  "zip": "122001",
  "phoneNumber": "9999999999",
  "email": "rishita.sharma@gmail.com"
}


### Delete Contact
DELETE http://localhost:8080/contacts/1
Accept: application/json
```
